In [3]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

In [4]:
doc =read_file('shakespeare.txt')

In [5]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [6]:
nlp = spacy.load('en_core_web_sm', disable=['parser', 'tagger', 'ner'])

In [7]:
nlp.max_length = 1198623

In [8]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [9]:
tokens = separate_punc(doc)

C:\Users\yashu\anaconda3\lib\site-packages\spacy\pipeline\lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [10]:
tokens

['first',
 'citizen',
 'before',
 'we',
 'proceed',
 'any',
 'further',
 'hear',
 'me',
 'speak',
 'all',
 'speak',
 'speak',
 'first',
 'citizen',
 'you',
 'are',
 'all',
 'resolved',
 'rather',
 'to',
 'die',
 'than',
 'to',
 'famish',
 'all',
 'resolved',
 'resolved',
 'first',
 'citizen',
 'first',
 'you',
 'know',
 'caius',
 'marcius',
 'is',
 'chief',
 'enemy',
 'to',
 'the',
 'people',
 'all',
 'we',
 "know't",
 'we',
 "know't",
 'first',
 'citizen',
 'let',
 'us',
 'kill',
 'him',
 'and',
 'we',
 "'ll",
 'have',
 'corn',
 'at',
 'our',
 'own',
 'price',
 "is't",
 'a',
 'verdict',
 'all',
 'no',
 'more',
 'talking',
 "on't",
 'let',
 'it',
 'be',
 'done',
 'away',
 'away',
 'second',
 'citizen',
 'one',
 'word',
 'good',
 'citizens',
 'first',
 'citizen',
 'we',
 'are',
 'accounted',
 'poor',
 'citizens',
 'the',
 'patricians',
 'good',
 'what',
 'authority',
 'surfeits',
 'on',
 'would',
 'relieve',
 'us',
 'if',
 'they',
 'would',
 'yield',
 'us',
 'but',
 'the',
 'superfluity

In [11]:
len(tokens)

207859

In [12]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [13]:
text_sequences[1]

['citizen',
 'before',
 'we',
 'proceed',
 'any',
 'further',
 'hear',
 'me',
 'speak',
 'all',
 'speak',
 'speak',
 'first',
 'citizen',
 'you',
 'are',
 'all',
 'resolved',
 'rather',
 'to',
 'die',
 'than',
 'to',
 'famish',
 'all',
 'resolved']

In [14]:
' '.join(text_sequences[0])

'first citizen before we proceed any further hear me speak all speak speak first citizen you are all resolved rather to die than to famish all'

In [15]:
' '.join(text_sequences[1])

'citizen before we proceed any further hear me speak all speak speak first citizen you are all resolved rather to die than to famish all resolved'

In [16]:
' '.join(text_sequences[2])

'before we proceed any further hear me speak all speak speak first citizen you are all resolved rather to die than to famish all resolved resolved'

In [17]:
len(text_sequences)

207833

In [18]:
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer


In [19]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [20]:
sequences[0]

[93,
 275,
 142,
 33,
 991,
 147,
 673,
 133,
 17,
 112,
 35,
 112,
 112,
 93,
 275,
 6,
 42,
 35,
 1322,
 357,
 4,
 204,
 67,
 4,
 3872,
 35]

In [21]:
tokenizer.index_word

{1: 'the',
 2: 'and',
 3: 'i',
 4: 'to',
 5: 'of',
 6: 'you',
 7: 'my',
 8: 'a',
 9: 'that',
 10: 'in',
 11: 'not',
 12: 'is',
 13: 'for',
 14: "'s",
 15: 'with',
 16: 'it',
 17: 'me',
 18: 'be',
 19: 'your',
 20: 'he',
 21: 'his',
 22: 'this',
 23: 'but',
 24: "'",
 25: 'have',
 26: 'as',
 27: 'thou',
 28: 'him',
 29: 'what',
 30: 'so',
 31: 'thy',
 32: 'will',
 33: 'we',
 34: 'king',
 35: 'all',
 36: 'by',
 37: 'no',
 38: 'shall',
 39: 'her',
 40: 'if',
 41: 'our',
 42: 'are',
 43: 'do',
 44: 'thee',
 45: 'lord',
 46: 'now',
 47: 'on',
 48: 'good',
 49: 'o',
 50: 'come',
 51: 'from',
 52: 'sir',
 53: 'or',
 54: 'which',
 55: "'ll",
 56: 'more',
 57: 'then',
 58: 'at',
 59: 'here',
 60: 'she',
 61: 'they',
 62: 'would',
 63: 'was',
 64: 'let',
 65: 'how',
 66: 'well',
 67: 'than',
 68: 'their',
 69: 'them',
 70: 'duke',
 71: 'can',
 72: 'am',
 73: 'hath',
 74: 'say',
 75: 'when',
 76: 'there',
 77: 'love',
 78: 'one',
 79: 'go',
 80: 'were',
 81: 'may',
 82: 'us',
 83: 'make',
 84: 'u

In [22]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

93 : first
275 : citizen
142 : before
33 : we
991 : proceed
147 : any
673 : further
133 : hear
17 : me
112 : speak
35 : all
112 : speak
112 : speak
93 : first
275 : citizen
6 : you
42 : are
35 : all
1322 : resolved
357 : rather
4 : to
204 : die
67 : than
4 : to
3872 : famish
35 : all


In [23]:
tokenizer.word_counts

OrderedDict([('first', 9401),
             ('citizen', 2565),
             ('before', 5047),
             ('we', 24626),
             ('proceed', 525),
             ('any', 4894),
             ('further', 917),
             ('hear', 5936),
             ('me', 45821),
             ('speak', 7575),
             ('all', 23585),
             ('you', 82930),
             ('are', 20401),
             ('resolved', 383),
             ('rather', 1975),
             ('to', 127471),
             ('die', 3590),
             ('than', 12477),
             ('famish', 103),
             ('know', 9152),
             ('caius', 442),
             ('marcius', 3172),
             ('is', 54054),
             ('chief', 182),
             ('enemy', 1144),
             ('the', 163436),
             ('people', 2548),
             ("know't", 156),
             ('let', 13598),
             ('us', 10374),
             ('kill', 1274),
             ('him', 31434),
             ('and', 147777),
             ("'ll", 1

In [24]:
vocabulary_size = len(tokenizer.word_counts)

In [25]:
vocabulary_size


12327

In [26]:
import numpy as np

In [27]:
sequences = np.array(sequences)

In [28]:
sequences

array([[   93,   275,   142, ...,     4,  3872,    35],
       [  275,   142,    33, ...,  3872,    35,  1322],
       [  142,    33,   991, ...,    35,  1322,  1322],
       ...,
       [   18,  1405,    15, ...,   357, 12327,  1084],
       [ 1405,    15,   191, ..., 12327,  1084,    27],
       [   15,   191,  2029, ...,  1084,    27,   134]])

In [29]:
from keras.utils import to_categorical

In [30]:

sequences[:,:-1]

array([[   93,   275,   142, ...,    67,     4,  3872],
       [  275,   142,    33, ...,     4,  3872,    35],
       [  142,    33,   991, ...,  3872,    35,  1322],
       ...,
       [   18,  1405,    15, ...,   204,   357, 12327],
       [ 1405,    15,   191, ...,   357, 12327,  1084],
       [   15,   191,  2029, ..., 12327,  1084,    27]])

In [31]:
sequences[:,-1]

array([  35, 1322, 1322, ..., 1084,   27,  134])

In [32]:
X = sequences[:,:-1]

In [33]:
y = sequences[:,-1]

In [34]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [35]:
seq_len = X.shape[1]

In [36]:
seq_len

25

In [37]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [38]:
import tensorflow as tf

def create_model(vocabulary_size, seq_len):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Embedding(vocabulary_size, 25))
    model.add(tf.keras.layers.LSTM(150, return_sequences=True))
    model.add(tf.keras.layers.LSTM(150))
    model.add(tf.keras.layers.Dense(150, activation='relu'))
    model.add(tf.keras.layers.Dense(vocabulary_size, activation='softmax'))
    
    model.build((None, seq_len))  # Build the model specifying input shape
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model



In [39]:
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 25, 25)         │       308,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 25, 150)        │       105,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       180,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 150)            │        22,650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12328)          │     1,861,528 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,478,578 (9.46 MB)

 Trainable params: 2,478,578 (9.46 MB)

 Non-trainable params: 0 (0.00 B)

In [40]:
from pickle import dump,load

In [71]:
model.fit(X, y, batch_size=128, epochs=300,verbose=1)

Epoch 1/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 255s 157ms/step - accuracy: 0.2374 - loss: 3.5949
Epoch 2/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 248s 153ms/step - accuracy: 0.2485 - loss: 3.5023
Epoch 3/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 522s 321ms/step - accuracy: 0.2513 - loss: 3.4872
Epoch 4/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 975s 565ms/step - accuracy: 0.2546 - loss: 3.4626
Epoch 5/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 265s 163ms/step - accuracy: 0.2613 - loss: 3.4291
Epoch 6/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 252s 155ms/step - accuracy: 0.2632 - loss: 3.4127
Epoch 7/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 762s 469ms/step - accuracy: 0.2661 - loss: 3.3921
Epoch 8/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 1235s 761ms/step - accuracy: 0.2711 - loss: 3.3651
Epoch 9/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 284s 175ms/step - accuracy: 0.2743 - loss: 3.3485
Epoch 10/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 287s 177ms/step - accuracy: 0.2771 - loss: 3.3247
Epoch 11/300
1624/1624 ━━━━━━━━━━━━━━━━━━━━ 439s 270ms/step - accura

KeyboardInterrupt: 

In [72]:
model.save('my_literature_model.keras')
# save the tokenizer
dump(tokenizer, open('my_literature_model', 'wb'))

In [73]:
from random import randint
from pickle import load

In [74]:
from keras.models import load_model

In [75]:
#from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.sequence import pad_sequences

In [76]:
def generate_text(model, tokenizer, seq_len, seed_text, num_lines=3, words_per_line=10):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_lines : number of lines to be generated
    words_per_line : number of words per line to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Create num_lines
    for _ in range(num_lines):
        # Initial Seed Sequence
        input_text = seed_text
        
        # Create words_per_line
        for _ in range(words_per_line):
            # Take the input text string and encode it to a sequence
            encoded_text = tokenizer.texts_to_sequences([input_text])[0]
            
            # Pad sequences to our trained rate 
            pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
            
            # Predict Class Probabilities for each word
            pred_probabilities = model.predict(pad_encoded, verbose=0)[0]
            
            # Sample the index of the next word based on predicted probabilities
            next_word_index = np.random.choice(len(pred_probabilities), p=pred_probabilities)
            
            # Convert index to word
            pred_word = tokenizer.index_word[next_word_index + 1]  # Adjust index by 1
            
            # Update the sequence of input text (shifting one over with the new word)
            input_text += ' ' + pred_word
            
            output_text.append(pred_word)
        
        # Add a newline after each line
        output_text.append('\n')
    
    # Make it look like multiple lines of text.
    return ' '.join(output_text)



In [77]:
text_sequences[0]

['first',
 'citizen',
 'before',
 'we',
 'proceed',
 'any',
 'further',
 'hear',
 'me',
 'speak',
 'all',
 'speak',
 'speak',
 'first',
 'citizen',
 'you',
 'are',
 'all',
 'resolved',
 'rather',
 'to',
 'die',
 'than',
 'to',
 'famish',
 'all']

In [78]:
import random
#random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [79]:
random_seed_text = text_sequences[random_pick]

In [80]:
random_seed_text

['thou',
 'hast',
 'promised',
 'which',
 'is',
 'not',
 'yet',
 "perform'd",
 'me',
 'prospero',
 'how',
 'now',
 'moody',
 'what',
 "is't",
 'thou',
 'canst',
 'demand',
 'ariel',
 'my',
 'liberty',
 'prospero',
 'before',
 'the',
 'time',
 'be']

In [81]:
seed_text = ' '.join(random_seed_text)

In [82]:
seed_text

"thou hast promised which is not yet perform'd me prospero how now moody what is't thou canst demand ariel my liberty prospero before the time be"

In [83]:
generated_text = generate_text(model, tokenizer, seq_len, seed_text=seed_text, num_lines=3, words_per_line=25)
print(generated_text)


honour a wo shame 's comfort i was out not if to moral father than sighs i apparent if land dagger i holy and anon 
 ay thou comfort when a world hap ' see ourself 's dolour place to be that up of lord are seas thou escalus have from 
 second half is thy severe in a all tongue another woman who tender who curse have freezeth seem'd thy night i sincerely had here that 

